### ISSUE TITLE
Events Calendar        

### ISSUE THREAD

**Issue by Barbanio** [asyncapi/marketing#3]
Hello everyone, @Alejandrolmiguel and I have thought that it might be a good idea to have a record of events that may be of interest to AsynAPI. Is there anything done about this previously? Do you know specific websites to check? @derberg  , do you get anything on this? Thanks a lot 🙂.

https://docs.google.com/spreadsheets/d/1tg3dOu-wVw44JadYtC456mfb2rRHQZsr/edit?usp=drive_web&ouid=105782233104866345736&rtpof=true

**Comment by fmvilas** [comment]
Have you considered doing this as a Google Sheet instead of a Google Doc?

**Comment by derberg** [comment]
I never created any list about it. This would be awesome. This year at our first open meeting one of our community members asked if we have `events calendar for 2021` which sounded like a good idea and something we need to get. There are many events we can put there on the list

I recommend Google Sheet like @fmvilas because this way it will be easier to sort and filter out data

**Comment by Barbanio** [comment]
Great, I will move the information to a Google Sheet

**Comment by AlejandrolMiguel** [comment]
Thanks guys! we'll start working on it.

**Comment by Barbanio** [comment]
Hello everyone, @Alejandrolmiguel and I were making a list of events that could be of interest to the project and suddenly we found this wonderful calendar https://cfpcalendar.com/, so thanks to @MarcDiPasquale we don't have to do it. Thank you @MarcDiPasquale :)
