### ISSUE TITLE
To make press kit

### ISSUE THREAD

**Issue by Barbanio** [asyncapi/marketing#7]
Hi everyone! @Alejandrolmiguel and I have thought about creating a press kit, we think it is a good idea for the project to have handy information when dealing with media.

**Comment by derberg** [comment]
I only have concerns about how that would scale. The initiative is cool but what about other community members that actively work on a project?
I mean what is the "team" and where do you see this description should be?

I think better would be that we first form an open governance model for the project, set the list of all the committers (people that maintain all projects), and publish it somewhere on our website (has to be automated, and should not be hard to do)

**Comment by Barbanio** [comment]
I think it's a good idea, we hope so. Regarding the team, we don't know where to draw the line, that's why we have limited ourselves to mentioning those of you who are part of the project full time.

I think it's great to put it on the website and make it automatic, but we need to have a document for the press that briefly explains who is behind the project and put some names and ideas about it.

**Comment by jonaslagoni** [comment]
I agree with @derberg here. Since this project cannot be seen as a company we cannot use the terms `team`, I think we should see it as what it is a community. 

We are a community where some work full time, some work part-time, some use their limited spare time to contribute where all should be recognized as part of the community as a whole. 

But depending on the open governance model, we could do some recognition of companies dedicating developers and who those developers are etc. Basically what you suggested @Barbanio 😄

**Comment by Barbanio** [comment]
Thanks @jonaslagoni, we will work on this idea :)

**Comment by Barbanio** [comment]
Hello everybody, we leave you the sketch of the press kitt, we are waiting for your contributions. Thanks in advance :)
https://docs.google.com/document/d/1U3k_YnMIdJUaTmw16X6CZR5KPMgl0_Ml/edit#heading=h.gjdgxs

**Comment by Barbanio** [comment]
This is the Spanish version that we are working on.
https://docs.google.com/document/d/1yCmhfntfSJ6IVSScDTbWpHQaQbtHdWdNZv9f_g0JVSM/edit#
